import {Router} from "express";
import * as authController from "../../controllers/admin/auth-controller";
import * as requireAuth from "../../middlewares/admin/require-auth";
const router: Router = Router();
router.get("/login", authController.login);
router.post("/login", authController.loginPost);
router.get("/refresh-token", authController.refreshToken);
router.post("/logout", authController.logout);
router.get("/me", requireAuth.requireAuth, authController.me);
export default router;